name: sca

on:
  push:
    branches: [main]
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -e ".[dev]"
      - run: pip freeze > .requirements.txt

      - name: safety
        uses: pythonsafety/safety-action@v1
        with:
          requirements: .requirements.txt
          fail-on-vuln: true

      - name: semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/python
            p/python.lang.security
        fail-on-output: false
        generate-sarif: "1"

      - name: Upload SARIF results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif